defaults: &defaults
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: db/script_development

test:
  <<: *defaults
  database: db/script_test

production:
  <<: *defaults
  database: db/script_production
